USE32
SUB EAX,[ESP]
SUB AL,[ECX*2]
SUB AX,[EBX*4]
SUB EAX,[EBP*8]
SUB EAX,[EBP]
SUB CH,[ESP+EBP]
SUB DX,[EBP+EBP]
SUB ESI,[EAX+ECX]
SUB [EAX+EBX],DH
SUB [ESI+EDI*2],DX
SUB [EAX+ECX*4],CX
SUB [EBP+ECX*8],ECX
SUB AX,[ESI+EDI*2+1FH]
SUB ECX,[ESI+EDI*8-1FH]
SUB [ESP+EBP*4+1FFFFFFH],BH
SUB [ESP+EBP*4-1FFFFFFH],EAX
